### PR TITLE
check arguments, return error instead of raising exceptions. 

### LINKED ISSUE #1117: Segementation fault when setting FS register to any value above 0x3
When initializing the FS segment register to anything above 0x3, unicorn segfaults. This doesn't happen when unicorn is initialized with `UC_MODE_64`. 

```
Python 3.7.3 (default, Jun 24 2019, 04:54:02) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.6.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from unicorn import *                                                                                                           
In [2]: from unicorn.x86_const import *                                                                                                 
In [3]: uc = Uc(UC_ARCH_X86, UC_MODE_32)                                                                                                
In [4]: uc.reg_write(UC_X86_REG_FS, 0x3)                                                                                                
In [5]: uc.reg_write(UC_X86_REG_FS, 0x4)                                                                                                
Segmentation fault (core dumped)
```

### PR DESCRIPTION
**Pull request by chenhuitao**
close #1117.
Writing the segment registers directly probably cause the emulator crash, and python can not catch the exceptions which runs in C.
Add _uc_check_cpu_x86_load_seg() before run cpu_x86_load_seg(), check the arguments , return error instead of raising exceptions. Python will check the return value, raise local language exception on error.

### CODE REVIEW

**Comment by chenhuitao** [comment]
close and re-open for AppVeyor checking.

**Comment by Waterman178** [comment]
thanks

File: qemu/target-i386/seg_helper.c [hunk 1]
```diff
@@ -1539,6 +1539,87 @@ void helper_ltr(CPUX86State *env, int selector)
...
+    uint32_t e2;
+    int cpl, dpl, rpl;
+    SegmentCache *dt;
+    int index;
+    target_ulong ptr;
+
+    if (!(env->cr[0] & CR0_PE_MASK) || (env->eflags & VM_MASK)) {
+        return 0;
+    } else {
+
```
Comment (aquynh) [inline qemu/target-i386/seg_helper.c]: please remove this blank line

File: qemu/target-i386/seg_helper.c [hunk 2]
```diff
@@ -1539,6 +1539,87 @@ void helper_ltr(CPUX86State *env, int selector)
...
+            if (seg_reg == R_SS
+#ifdef TARGET_X86_64
+                && (!(env->hflags & HF_CS64_MASK) || cpl == 3)
+#endif
+                ) {
+                return UC_ERR_EXCEPTION;
+            }
+            return 0;
+        } else {
+
```
Comment (aquynh) [inline qemu/target-i386/seg_helper.c]: and this blank line

File: qemu/target-i386/seg_helper.c [hunk 3]
```diff
@@ -1539,6 +1539,87 @@ void helper_ltr(CPUX86State *env, int selector)
...
+            }
+
+            if (!(e2 & DESC_P_MASK)) {
+                if (seg_reg == R_SS) {
+                    return UC_ERR_EXCEPTION;
+                } else {
+                    return UC_ERR_EXCEPTION;
+                }
+            }
+
```
Comment (aquynh) [inline qemu/target-i386/seg_helper.c]: and this blank line

File: qemu/target-i386/cpu.h [hunk 4]
```diff
@@ -1137,6 +1137,10 @@ void cpu_x86_load_seg(CPUX86State *s, int seg_reg, int selector);
 void cpu_x86_fsave(CPUX86State *s, target_ulong ptr, int data32);
 void cpu_x86_frstor(CPUX86State *s, target_ulong ptr, int data32);
 
+/*  the binding language can not catch the exceptions.
+    check the arguments, return error instead of raise exceptions. */
+int _uc_check_cpu_x86_load_seg(CPUX86State *env, int seg_reg, int sel);
```
Comment (aquynh) [inline qemu/target-i386/cpu.h]: how about removing the prefix _ in function name?

File: uc.c [hunk 5]
```diff
@@ -371,12 +371,13 @@ uc_err uc_reg_read_batch(uc_engine *uc, int *ids, void **vals, int count)
 UNICORN_EXPORT
 uc_err uc_reg_write_batch(uc_engine *uc, int *ids, void *const *vals, int count)
 {
+    int ret = UC_ERR_OK;
     if (uc->reg_write)
-        uc->reg_write(uc, (unsigned int *)ids, vals, count);
+        ret = uc->reg_write(uc, (unsigned int *)ids, vals, count);
     else
-        return -1;  // FIXME: need a proper uc_err
+        return UC_ERR_EXCEPTION;  // FIXME: need a proper uc_err
```
Comment (aquynh) [inline uc.c]: we have UC_ERR_ARG, but that may not be a good choice. 

what can be a better error code for this case?

File: qemu/target-i386/cpu.h (hunk 4 above)
Comment (chenhuitao) [reply qemu/target-i386/cpu.h]: Function name with underscore prefix means it is reserved, not public. Keep it is better.

Comment (aquynh) [reply qemu/target-i386/cpu.h]: i know, but this is definitely not C convention ;-)

we never use this convention anywhere in Unicorn code, either.

File: uc.c (hunk 5 above)
Comment (chenhuitao) [reply uc.c]: In current definition of error code, I think the UC_ERR_EXCEPTION is the best. If this function failed, you have to catch the exception or terminate program.

File: qemu/target-i386/cpu.h (hunk 4 above)
Comment (chenhuitao) [reply qemu/target-i386/cpu.h]: O.K. Remove the underscore.

**Comment by aquynh** [comment]
merged, thanks!
